export default {
  ranged: {
    User: 'User',
    Session: 'Session',
    MessageSession: 'MessageSession',
    MessageCount: 'MessageCount',
    MessageUser: 'MessageUser',
  },
  date: {},
  global: {
    Gender: 'Gender',
    Country: 'Country',
    Locale: 'Locale',
    ResponseDelay: 'ResponseDelay',
    ReadDelay: 'ReadDelay',
    ProfileAge: 'ProfileAge',
  },
  metricType: {
    PROFILE_AGE: 'ProfileAge',
    MESSAGE_COUNT: 'MessageCount',
    MESSAGE_COUNT_SUMMARY: 'MessageCountSummary',
    READ_DELAY: 'ReadDelay',
    RESPONSE_DELAY: 'ResponseDelay',
    COUNTRY: 'Country',
    LOCALE:'Locale',
    LOCALE_TABULAR_DATA:'LocaleTable',
    GENDER: 'Gender',
    USER: 'User',
    USER_CHANGE: 'UserChange',
    USER_CHANGE_SUMMARY: 'UserChangeSummary',
    MESSAGE_SESSION: 'MessageSession',
    MESSAGE_USER: 'MessageUser',
    MESSAGE_SESSION_ENGAGED: 'MessageSessionEngaged',
    MESSAGE_SESSION_ENGAGED_SUMMARY: 'MessageSessionEngagedSummary',
    MESSAGE_ENGAGEMENT: 'MessageEngagement',
    MESSAGE_ENGAGEMENT_SUMMARY: 'MessageEngagementSummary',
    SESSION: 'Session',
    SENT_MESSAGES: 'SentMessages',
    SENT_MESSAGES_SUMMARY: 'SentMessagesSummary',
    OVERVIEW: 'Overview',
    TIME_ZONE: 'TimeZone',
    TIME_ZONE_TABULAR_DATA: 'TimeZoneTable',
    RETENTION: 'Retention',
    SUBSCRIPTION_CHANGE: 'SubscriptionChange',
    SUBSCRIPTION_CHANGE_SUMMARY: 'SubscriptionChangeSummary',
    DELIVERY_TIME: 'DeliveryTime',
    DELIVERY_TIME_SUMMARY: 'DeliveryTimeSummary',
    READ_TIME: 'ReadTime',
    READ_TIME_SUMMARY: 'ReadTimeSummary',
    ENGAGEMENT_TIME: 'EngagementTime',
    ENGAGEMENT_TIME_SUMMARY: 'EngagementTimeSummary',
    TOP_NODES: 'TopNodes',
    TOP_NODES_SUMMARY: 'TopNodesSummary',
    TOP_ACTIONS: 'TopActions',
    TOP_TEXT_INPUTS: 'TopTextInputs',
    TOP_CONTENT_ITEMS: 'TopContentItems',
    REFERRALS: 'Referrals',
    REFERRALS_SUMMARY: 'ReferralsSummary',
    NODE_ANALYSIS: 'NodeAnalysis'
  }
};
